// Code generated by protoc-gen-go. DO NOT EDIT.
// source: sleepymemory/sleepymemory.proto

package sleepymemory

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	duration "github.com/golang/protobuf/ptypes/duration"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type SleepRequest struct {
	// The duration the request will sleep.
	SleepDuration *duration.Duration `protobuf:"bytes,1,opt,name=sleep_duration,json=sleepDuration,proto3" json:"sleep_duration,omitempty"`
	// Bytes of memory that will be allocated before sleeping to simulate requests that use lots of memory.
	WasteBytes           int64    `protobuf:"varint,2,opt,name=waste_bytes,json=wasteBytes,proto3" json:"waste_bytes,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SleepRequest) Reset()         { *m = SleepRequest{} }
func (m *SleepRequest) String() string { return proto.CompactTextString(m) }
func (*SleepRequest) ProtoMessage()    {}
func (*SleepRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_acb602be93028508, []int{0}
}

func (m *SleepRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SleepRequest.Unmarshal(m, b)
}
func (m *SleepRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SleepRequest.Marshal(b, m, deterministic)
}
func (m *SleepRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SleepRequest.Merge(m, src)
}
func (m *SleepRequest) XXX_Size() int {
	return xxx_messageInfo_SleepRequest.Size(m)
}
func (m *SleepRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SleepRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SleepRequest proto.InternalMessageInfo

func (m *SleepRequest) GetSleepDuration() *duration.Duration {
	if m != nil {
		return m.SleepDuration
	}
	return nil
}

func (m *SleepRequest) GetWasteBytes() int64 {
	if m != nil {
		return m.WasteBytes
	}
	return 0
}

type SleepResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SleepResponse) Reset()         { *m = SleepResponse{} }
func (m *SleepResponse) String() string { return proto.CompactTextString(m) }
func (*SleepResponse) ProtoMessage()    {}
func (*SleepResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_acb602be93028508, []int{1}
}

func (m *SleepResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SleepResponse.Unmarshal(m, b)
}
func (m *SleepResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SleepResponse.Marshal(b, m, deterministic)
}
func (m *SleepResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SleepResponse.Merge(m, src)
}
func (m *SleepResponse) XXX_Size() int {
	return xxx_messageInfo_SleepResponse.Size(m)
}
func (m *SleepResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_SleepResponse.DiscardUnknown(m)
}

var xxx_messageInfo_SleepResponse proto.InternalMessageInfo

func init() {
	proto.RegisterType((*SleepRequest)(nil), "sleepymemory.SleepRequest")
	proto.RegisterType((*SleepResponse)(nil), "sleepymemory.SleepResponse")
}

func init() {
	proto.RegisterFile("sleepymemory/sleepymemory.proto", fileDescriptor_acb602be93028508)
}

var fileDescriptor_acb602be93028508 = []byte{
	// 232 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x90, 0xc1, 0x4a, 0x03, 0x31,
	0x10, 0x86, 0x59, 0x45, 0x85, 0x69, 0xab, 0x90, 0x53, 0x5d, 0xc1, 0x96, 0x9e, 0x7a, 0x31, 0x81,
	0xfa, 0x02, 0xa5, 0x78, 0xf3, 0xb6, 0xde, 0xbc, 0x94, 0xcd, 0x3a, 0xae, 0x91, 0x4d, 0x66, 0x9b,
	0x4c, 0x94, 0x7d, 0x7b, 0x69, 0xb6, 0x0b, 0x5b, 0xf0, 0x96, 0xf9, 0xe6, 0x9b, 0x3f, 0x99, 0xc0,
	0x22, 0x34, 0x88, 0x6d, 0x67, 0xd1, 0x92, 0xef, 0xd4, 0xb8, 0x90, 0xad, 0x27, 0x26, 0x31, 0x1d,
	0xb3, 0xfc, 0xb1, 0x26, 0xaa, 0x1b, 0x54, 0xa9, 0xa7, 0xe3, 0xa7, 0xfa, 0x88, 0xbe, 0x64, 0x43,
	0xae, 0xb7, 0x57, 0x07, 0x98, 0xbe, 0x1d, 0xfd, 0x02, 0x0f, 0x11, 0x03, 0x8b, 0x2d, 0xdc, 0xa6,
	0xf9, 0xfd, 0xe0, 0xcd, 0xb3, 0x65, 0xb6, 0x9e, 0x6c, 0xee, 0x65, 0x1f, 0x24, 0x87, 0x20, 0xf9,
	0x72, 0x12, 0x8a, 0x59, 0x1a, 0x18, 0x4a, 0xb1, 0x80, 0xc9, 0x6f, 0x19, 0x18, 0xf7, 0xba, 0x63,
	0x0c, 0xf3, 0x8b, 0x65, 0xb6, 0xbe, 0x2c, 0x20, 0xa1, 0xdd, 0x91, 0xac, 0xee, 0x60, 0x76, 0xba,
	0x32, 0xb4, 0xe4, 0x02, 0x6e, 0x5e, 0xe1, 0x26, 0x01, 0xf4, 0x62, 0x0b, 0x57, 0xe9, 0x28, 0x72,
	0x79, 0xb6, 0xda, 0xf8, 0x8d, 0xf9, 0xc3, 0xbf, 0xbd, 0x3e, 0x6c, 0xa7, 0xde, 0x9f, 0x6a, 0xc3,
	0x5f, 0x51, 0xcb, 0x8a, 0xac, 0xc2, 0x9f, 0xd2, 0x7d, 0xab, 0x8a, 0x5c, 0x15, 0xbd, 0x47, 0xc7,
	0x8d, 0xb1, 0x86, 0xcf, 0x7e, 0x4d, 0x5f, 0xa7, 0x8d, 0x9e, 0xff, 0x02, 0x00, 0x00, 0xff, 0xff,
	0x77, 0xe2, 0x41, 0xe8, 0x59, 0x01, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// SleeperClient is the client API for Sleeper service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type SleeperClient interface {
	Sleep(ctx context.Context, in *SleepRequest, opts ...grpc.CallOption) (*SleepResponse, error)
}

type sleeperClient struct {
	cc grpc.ClientConnInterface
}

func NewSleeperClient(cc grpc.ClientConnInterface) SleeperClient {
	return &sleeperClient{cc}
}

func (c *sleeperClient) Sleep(ctx context.Context, in *SleepRequest, opts ...grpc.CallOption) (*SleepResponse, error) {
	out := new(SleepResponse)
	err := c.cc.Invoke(ctx, "/sleepymemory.Sleeper/Sleep", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SleeperServer is the server API for Sleeper service.
type SleeperServer interface {
	Sleep(context.Context, *SleepRequest) (*SleepResponse, error)
}

// UnimplementedSleeperServer can be embedded to have forward compatible implementations.
type UnimplementedSleeperServer struct {
}

func (*UnimplementedSleeperServer) Sleep(ctx context.Context, req *SleepRequest) (*SleepResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Sleep not implemented")
}

func RegisterSleeperServer(s *grpc.Server, srv SleeperServer) {
	s.RegisterService(&_Sleeper_serviceDesc, srv)
}

func _Sleeper_Sleep_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SleepRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SleeperServer).Sleep(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/sleepymemory.Sleeper/Sleep",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SleeperServer).Sleep(ctx, req.(*SleepRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Sleeper_serviceDesc = grpc.ServiceDesc{
	ServiceName: "sleepymemory.Sleeper",
	HandlerType: (*SleeperServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Sleep",
			Handler:    _Sleeper_Sleep_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "sleepymemory/sleepymemory.proto",
}
