// Code generated by protoc-gen-go. DO NOT EDIT.
// source: sleepymemory/sleepymemory.proto

package sleepymemory

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	duration "github.com/golang/protobuf/ptypes/duration"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type SleepRequest struct {
	// The duration the request will sleep.
	SleepTime *duration.Duration `protobuf:"bytes,1,opt,name=sleep_time,json=sleepTime,proto3" json:"sleep_time,omitempty"`
	// Bytes of memory that will be allocated before sleeping to simulate requests that use lots of memory.
	Created              int64    `protobuf:"varint,2,opt,name=created,proto3" json:"created,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SleepRequest) Reset()         { *m = SleepRequest{} }
func (m *SleepRequest) String() string { return proto.CompactTextString(m) }
func (*SleepRequest) ProtoMessage()    {}
func (*SleepRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_acb602be93028508, []int{0}
}

func (m *SleepRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SleepRequest.Unmarshal(m, b)
}
func (m *SleepRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SleepRequest.Marshal(b, m, deterministic)
}
func (m *SleepRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SleepRequest.Merge(m, src)
}
func (m *SleepRequest) XXX_Size() int {
	return xxx_messageInfo_SleepRequest.Size(m)
}
func (m *SleepRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SleepRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SleepRequest proto.InternalMessageInfo

func (m *SleepRequest) GetSleepTime() *duration.Duration {
	if m != nil {
		return m.SleepTime
	}
	return nil
}

func (m *SleepRequest) GetCreated() int64 {
	if m != nil {
		return m.Created
	}
	return 0
}

type SleepResponse struct {
	// The duration the request will sleep.
	SleepTime *duration.Duration `protobuf:"bytes,1,opt,name=sleep_time,json=sleepTime,proto3" json:"sleep_time,omitempty"`
	// Bytes of memory that will be allocated before sleeping to simulate requests that use lots of memory.
	Created              int64    `protobuf:"varint,2,opt,name=created,proto3" json:"created,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SleepResponse) Reset()         { *m = SleepResponse{} }
func (m *SleepResponse) String() string { return proto.CompactTextString(m) }
func (*SleepResponse) ProtoMessage()    {}
func (*SleepResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_acb602be93028508, []int{1}
}

func (m *SleepResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SleepResponse.Unmarshal(m, b)
}
func (m *SleepResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SleepResponse.Marshal(b, m, deterministic)
}
func (m *SleepResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SleepResponse.Merge(m, src)
}
func (m *SleepResponse) XXX_Size() int {
	return xxx_messageInfo_SleepResponse.Size(m)
}
func (m *SleepResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_SleepResponse.DiscardUnknown(m)
}

var xxx_messageInfo_SleepResponse proto.InternalMessageInfo

func (m *SleepResponse) GetSleepTime() *duration.Duration {
	if m != nil {
		return m.SleepTime
	}
	return nil
}

func (m *SleepResponse) GetCreated() int64 {
	if m != nil {
		return m.Created
	}
	return 0
}

func init() {
	proto.RegisterType((*SleepRequest)(nil), "sleepymemory.SleepRequest")
	proto.RegisterType((*SleepResponse)(nil), "sleepymemory.SleepResponse")
}

func init() {
	proto.RegisterFile("sleepymemory/sleepymemory.proto", fileDescriptor_acb602be93028508)
}

var fileDescriptor_acb602be93028508 = []byte{
	// 230 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xb4, 0x50, 0xb1, 0x4e, 0xc3, 0x30,
	0x14, 0x54, 0x40, 0x50, 0xf1, 0x28, 0x8b, 0xa7, 0x10, 0x24, 0xa8, 0x3a, 0x75, 0xc1, 0x96, 0xca,
	0xc2, 0x88, 0x10, 0x1b, 0x5b, 0x60, 0x62, 0x41, 0xb1, 0xfb, 0x08, 0x46, 0xb1, 0x5f, 0xb0, 0x9f,
	0x91, 0xfa, 0xf7, 0x08, 0xa7, 0x95, 0x12, 0x89, 0xb5, 0x9b, 0xcf, 0x77, 0xbe, 0x3b, 0x1f, 0xdc,
	0xc4, 0x0e, 0xb1, 0xdf, 0x3a, 0x74, 0x14, 0xb6, 0x6a, 0x0c, 0x64, 0x1f, 0x88, 0x49, 0xcc, 0xc7,
	0x77, 0xd5, 0x75, 0x4b, 0xd4, 0x76, 0xa8, 0x32, 0xa7, 0xd3, 0x87, 0xda, 0xa4, 0xd0, 0xb0, 0x25,
	0x3f, 0xa8, 0x97, 0x1a, 0xe6, 0x2f, 0x7f, 0xfa, 0x1a, 0xbf, 0x13, 0x46, 0x16, 0xf7, 0x00, 0xf9,
	0xfd, 0x3b, 0x5b, 0x87, 0x65, 0xb1, 0x28, 0x56, 0xe7, 0xeb, 0x4b, 0x39, 0x98, 0xc8, 0xbd, 0x89,
	0x7c, 0xda, 0x99, 0xd4, 0x67, 0x59, 0xfc, 0x6a, 0x1d, 0x8a, 0x12, 0x66, 0x26, 0x60, 0xc3, 0xb8,
	0x29, 0x8f, 0x16, 0xc5, 0xea, 0xb8, 0xde, 0xc3, 0xa5, 0x81, 0x8b, 0x5d, 0x46, 0xec, 0xc9, 0x47,
	0x3c, 0x44, 0xc8, 0xfa, 0x19, 0x66, 0x39, 0x04, 0x83, 0x78, 0x80, 0x93, 0x7c, 0x14, 0x95, 0x9c,
	0xec, 0x33, 0xfe, 0x68, 0x75, 0xf5, 0x2f, 0x37, 0x14, 0x7c, 0x54, 0x6f, 0xb7, 0xad, 0xe5, 0xcf,
	0xa4, 0xa5, 0x21, 0xa7, 0xf0, 0xa7, 0xf1, 0x5f, 0xca, 0x90, 0x37, 0x29, 0x04, 0xf4, 0xdc, 0x59,
	0x67, 0x79, 0x32, 0xbd, 0x3e, 0xcd, 0xad, 0xef, 0x7e, 0x03, 0x00, 0x00, 0xff, 0xff, 0x7a, 0x39,
	0xb9, 0xfb, 0x9e, 0x01, 0x00, 0x00,
}
