// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v4.22.0
// source: sleepymemory/sleepymemory.proto

package sleepymemory

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	durationpb "google.golang.org/protobuf/types/known/durationpb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SleepRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// The duration the request will sleep.
	SleepDuration *durationpb.Duration `protobuf:"bytes,1,opt,name=sleep_duration,json=sleepDuration,proto3" json:"sleep_duration,omitempty"`
	// Bytes of memory that will be allocated before sleeping to simulate requests that use lots of memory.
	WasteBytes int64 `protobuf:"varint,2,opt,name=waste_bytes,json=wasteBytes,proto3" json:"waste_bytes,omitempty"`
}

func (x *SleepRequest) Reset() {
	*x = SleepRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_sleepymemory_sleepymemory_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SleepRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SleepRequest) ProtoMessage() {}

func (x *SleepRequest) ProtoReflect() protoreflect.Message {
	mi := &file_sleepymemory_sleepymemory_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SleepRequest.ProtoReflect.Descriptor instead.
func (*SleepRequest) Descriptor() ([]byte, []int) {
	return file_sleepymemory_sleepymemory_proto_rawDescGZIP(), []int{0}
}

func (x *SleepRequest) GetSleepDuration() *durationpb.Duration {
	if x != nil {
		return x.SleepDuration
	}
	return nil
}

func (x *SleepRequest) GetWasteBytes() int64 {
	if x != nil {
		return x.WasteBytes
	}
	return 0
}

type SleepResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// The value is ignored but exists to prevent garbage collection freeing the waste slice early.
	Ignored int64 `protobuf:"varint,1,opt,name=ignored,proto3" json:"ignored,omitempty"`
}

func (x *SleepResponse) Reset() {
	*x = SleepResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_sleepymemory_sleepymemory_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SleepResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SleepResponse) ProtoMessage() {}

func (x *SleepResponse) ProtoReflect() protoreflect.Message {
	mi := &file_sleepymemory_sleepymemory_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SleepResponse.ProtoReflect.Descriptor instead.
func (*SleepResponse) Descriptor() ([]byte, []int) {
	return file_sleepymemory_sleepymemory_proto_rawDescGZIP(), []int{1}
}

func (x *SleepResponse) GetIgnored() int64 {
	if x != nil {
		return x.Ignored
	}
	return 0
}

var File_sleepymemory_sleepymemory_proto protoreflect.FileDescriptor

var file_sleepymemory_sleepymemory_proto_rawDesc = []byte{
	0x0a, 0x1f, 0x73, 0x6c, 0x65, 0x65, 0x70, 0x79, 0x6d, 0x65, 0x6d, 0x6f, 0x72, 0x79, 0x2f, 0x73,
	0x6c, 0x65, 0x65, 0x70, 0x79, 0x6d, 0x65, 0x6d, 0x6f, 0x72, 0x79, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x12, 0x0c, 0x73, 0x6c, 0x65, 0x65, 0x70, 0x79, 0x6d, 0x65, 0x6d, 0x6f, 0x72, 0x79, 0x1a,
	0x1e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66,
	0x2f, 0x64, 0x75, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22,
	0x71, 0x0a, 0x0c, 0x53, 0x6c, 0x65, 0x65, 0x70, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12,
	0x40, 0x0a, 0x0e, 0x73, 0x6c, 0x65, 0x65, 0x70, 0x5f, 0x64, 0x75, 0x72, 0x61, 0x74, 0x69, 0x6f,
	0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x19, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x44, 0x75, 0x72, 0x61, 0x74, 0x69,
	0x6f, 0x6e, 0x52, 0x0d, 0x73, 0x6c, 0x65, 0x65, 0x70, 0x44, 0x75, 0x72, 0x61, 0x74, 0x69, 0x6f,
	0x6e, 0x12, 0x1f, 0x0a, 0x0b, 0x77, 0x61, 0x73, 0x74, 0x65, 0x5f, 0x62, 0x79, 0x74, 0x65, 0x73,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0a, 0x77, 0x61, 0x73, 0x74, 0x65, 0x42, 0x79, 0x74,
	0x65, 0x73, 0x22, 0x29, 0x0a, 0x0d, 0x53, 0x6c, 0x65, 0x65, 0x70, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x69, 0x67, 0x6e, 0x6f, 0x72, 0x65, 0x64, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x03, 0x52, 0x07, 0x69, 0x67, 0x6e, 0x6f, 0x72, 0x65, 0x64, 0x32, 0x4b, 0x0a,
	0x07, 0x53, 0x6c, 0x65, 0x65, 0x70, 0x65, 0x72, 0x12, 0x40, 0x0a, 0x05, 0x53, 0x6c, 0x65, 0x65,
	0x70, 0x12, 0x1a, 0x2e, 0x73, 0x6c, 0x65, 0x65, 0x70, 0x79, 0x6d, 0x65, 0x6d, 0x6f, 0x72, 0x79,
	0x2e, 0x53, 0x6c, 0x65, 0x65, 0x70, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1b, 0x2e,
	0x73, 0x6c, 0x65, 0x65, 0x70, 0x79, 0x6d, 0x65, 0x6d, 0x6f, 0x72, 0x79, 0x2e, 0x53, 0x6c, 0x65,
	0x65, 0x70, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42, 0x2f, 0x5a, 0x2d, 0x67, 0x69,
	0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x65, 0x76, 0x61, 0x6e, 0x6a, 0x2f, 0x63,
	0x6f, 0x6e, 0x63, 0x75, 0x72, 0x72, 0x65, 0x6e, 0x74, 0x6c, 0x69, 0x6d, 0x69, 0x74, 0x2f, 0x73,
	0x6c, 0x65, 0x65, 0x70, 0x79, 0x6d, 0x65, 0x6d, 0x6f, 0x72, 0x79, 0x62, 0x06, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x33,
}

var (
	file_sleepymemory_sleepymemory_proto_rawDescOnce sync.Once
	file_sleepymemory_sleepymemory_proto_rawDescData = file_sleepymemory_sleepymemory_proto_rawDesc
)

func file_sleepymemory_sleepymemory_proto_rawDescGZIP() []byte {
	file_sleepymemory_sleepymemory_proto_rawDescOnce.Do(func() {
		file_sleepymemory_sleepymemory_proto_rawDescData = protoimpl.X.CompressGZIP(file_sleepymemory_sleepymemory_proto_rawDescData)
	})
	return file_sleepymemory_sleepymemory_proto_rawDescData
}

var file_sleepymemory_sleepymemory_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_sleepymemory_sleepymemory_proto_goTypes = []interface{}{
	(*SleepRequest)(nil),        // 0: sleepymemory.SleepRequest
	(*SleepResponse)(nil),       // 1: sleepymemory.SleepResponse
	(*durationpb.Duration)(nil), // 2: google.protobuf.Duration
}
var file_sleepymemory_sleepymemory_proto_depIdxs = []int32{
	2, // 0: sleepymemory.SleepRequest.sleep_duration:type_name -> google.protobuf.Duration
	0, // 1: sleepymemory.Sleeper.Sleep:input_type -> sleepymemory.SleepRequest
	1, // 2: sleepymemory.Sleeper.Sleep:output_type -> sleepymemory.SleepResponse
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_sleepymemory_sleepymemory_proto_init() }
func file_sleepymemory_sleepymemory_proto_init() {
	if File_sleepymemory_sleepymemory_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_sleepymemory_sleepymemory_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SleepRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_sleepymemory_sleepymemory_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SleepResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_sleepymemory_sleepymemory_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_sleepymemory_sleepymemory_proto_goTypes,
		DependencyIndexes: file_sleepymemory_sleepymemory_proto_depIdxs,
		MessageInfos:      file_sleepymemory_sleepymemory_proto_msgTypes,
	}.Build()
	File_sleepymemory_sleepymemory_proto = out.File
	file_sleepymemory_sleepymemory_proto_rawDesc = nil
	file_sleepymemory_sleepymemory_proto_goTypes = nil
	file_sleepymemory_sleepymemory_proto_depIdxs = nil
}
