version: 2.1
jobs:
  build:
    docker:
      - image: golang:1.14.0-buster
    steps:
      - checkout
      # Allow access to docker commands: https://circleci.com/docs/2.0/building-docker-images/
      - setup_remote_docker
      - run:
          name: run tests
          command: ./circleci.sh
