version: 2.1

workflows:
  version: 2
  build_and_test:
    jobs:
      - test
      - test_docker_image

jobs:
  test:
    docker:
      - image: golang:1.14.0-buster
    steps:
      - checkout
      - run:
          name: run tests
          command: ./circleci.sh

  test_docker_image:
    docker:
      - image: cimg/base:edge
    steps:
      - checkout
      # Allow access to docker commands: https://circleci.com/docs/2.0/building-docker-images/
      - setup_remote_docker
      - run:
          name: verify that the Dockerfile works
          command: docker build .
